version: 2

sources:
  - name: raw_data
    description: "Raw data from the application"
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: caravelo_analytics
    tables:
      - name: providers
        description: "Transportation providers"
      - name: plans
        description: "Subscription plans"
      - name: users
        description: "End users with geographic data"
      - name: subscription_events
        description: "Events related to user subscriptions (creation, renewal, cancellation)"
      - name: currency_rates
        description: "Daily currency conversion rates to EUR"
