name: 'caravelo_analytics'
version: '1.0.0'
config-version: 2

profile: 'caravelo_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  caravelo_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  caravelo_analytics:
    +quote_columns: false
